<?php
/**
 * Easylife_Switcher extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE_EASYLIFE_SWITCHER.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category   	Easylife
 * @package	    Easylife_Switcher
 * @copyright   2013 - 2014 Marius Strajeru
 * @license	    http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * override the superProduct variable
 *
 * @category    Easylife
 * @package	    Easylife_Switcher
 */
?>
<?php
    /** @var Easylife_Switcher_Helper_Data $helper */
    $helper = Mage::helper('easylife_switcher');
?>
<?php if ($helper->isEnabledAdmin()) : ?>
<script type="text/javascript">
//<![CDATA[
    if (typeof superProduct != 'undefined'){
        var createEmptyUrl = superProduct.createEmptyUrl;
        var createNormalUrl = superProduct.createNormalUrl;
        var createQuickUrl = superProduct.createQuickUrl;
        var links = superProduct.links;
        //document.observe("dom:loaded", function() {
            superProduct = new Easylife.Switcher(
                superProduct.attributes,
                links,
                superProduct.idPrefix,
                superProduct.grid,
                superProduct.readonly,
                '<?php echo Easylife_Switcher_Helper_Data::DEFAULT_CONFIGURATION_ATTRIBUTE_CODE?>'
            );
            superProduct.createEmptyUrl = createEmptyUrl;
            superProduct.createNormalUrl = createNormalUrl;
            superProduct.createQuickUrl = createQuickUrl;
        //});
    }
//]]>
</script>
<?php endif;?>
